version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ".:/var/code"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - php
  php:
    build: "./docker/php"
    volumes:
      - ".:/var/code"
    links:
      - mariadb
  composer:
    image: composer
    command: "install"
    working_dir: "/var/code"
    volumes:
      - ".:/var/code"
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306" # Exposing port in dev for debugging
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "covidciasie"
    volumes:
      - "./CREATE_TABLES.sql:/docker-entrypoint-initdb.d/CREATE_TABLES.sql"
      - "./var/database:/var/lib/mysql"

